language: python
python:
  - "3.7"
cache: false
dist: xenial

install:
  # FIXME: Inline math is broken in upstream recommonmark
  - pip install git+https://github.com/chrisburr/recommonmark.git@patch-1
  - pip install -vv starterkit-ci==0.0.12
  - pip install -vv sphinx-copybutton
  - pip install -vv sphinx-markdown-tables
  - pip install -vv notedown

script:
  - starterkit_ci --allow-warnings build
  # - starterkit_ci check
  - notedown fast-sim-and-analysis/FccFastSimDelphes.md  -o build/html/fast-sim-and-analysis/FccFastSimDelphes.ipynb
  - notedown fast-sim-and-analysis/FccFastSimAnalysis.md  -o build/html/fast-sim-and-analysis/FccFastSimAnalysis.ipynb
  - notedown full-detector-simulations/FccCaloPerformance/FccCaloPerformance.md  -o build/html/full-detector-simulations/FccCaloPerformance/FccCaloPerformance.ipynb

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && starterkit_ci deploy

